/* 
    Properties
*/
export const ALL_PROPERTIES_LOADING = 'ALL_PROPERTIES_LOADING'
export const ALL_PROPERTIES_FAILED = 'ALL_PROPERTIES_FAILED'
export const ADD_ALL_PROPERTIES = 'ADD_ALL_PROPERTIES'

export const PROPERTIES_LOADING = 'PROPERTIES_LOADING'
export const PROPERTIES_FAILED = 'PROPERTIES_FAILED'

export const PROPERTY_CREATE_REQUEST = 'PROPERTY_CREATE_REQUEST'
export const PROPERTY_CREATE_SUCCESS = 'PROPERTY_CREATE_SUCCESS'
export const PROPERTY_CREATE_FAILED = 'PROPERTY_CREATE_FAILED' 

export const PROPERTY_DELETE_REQUEST = 'PROPERTY_DELETE_REQUEST'
export const PROPERTY_DELETE_SUCCESS = 'PROPERTY_DELETE_SUCCESS'
export const PROPERTY_DELETE_FAILED = 'PROPERTY_DELETE_FAILED'

export const PROPERTY_EDIT_REQUEST = 'PROPERTY_EDIT_REQUEST'
export const PROPERTY_EDIT_SUCCESS = 'PROPERTY_EDIT_SUCCESS'
export const PROPERTY_EDIT_FAILED = 'PROPERTY_EDIT_FAILED'
export const PROPERTY_EDIT_RESET = 'PROPERTY_EDIT_RESET'

export const PROPERTY_FETCH_SINGLE_REQUEST = 'PROPERTY_FETCH_SINGLE_REQUEST'
export const PROPERTY_FETCH_SINGLE_SUCCESS = 'PROPERTY_FETCH_SINGLE_SUCCESS'
export const PROPERTY_FETCH_SINGLE_FAILED = 'PROPERTY_FETCH_SINGLE_FAILED'
export const PROPERTY_FETCH_SINGLE_RESET = 'PROPERTY_FETCH_SINGLE_RESET'

export const ADD_PROPERTIES = 'ADD_PROPERTIES'
export const DELETE_PROPERTY = 'DELETE_PROPERTY' 
export const BUY_PROPERTIES_LOADING = 'BUY_PROPERTIES_LOADING'
export const BUY_PROPERTIES_FAILED = 'BUY_PROPERTIES_FAILED'
export const ADD_PROPERTIES_BUY = 'ADD_PROPERTIES_BUY'
export const RENT_PROPERTIES_LOADING = 'RENT_PROPERTIES_LOADING'
export const RENT_PROPERTIES_FAILED = '_RENT_PROPERTIES_FAILED'
export const ADD_PROPERTIES_RENT = 'ADD_PROPERTIES_RENT'

export const MAKE_REQUEST_PROPERTIES_RENT = 'MAKE_REQUEST_PROPERTIES_RENT'
export const UPDATE_HAS_NEXT_PAGE_PROPERTIES_RENT = 'UPDATE_HAS_NEXT_PAGE_PROPERTIES_RENT'
export const UPDATE_HAS_NEXT_NEXT_PAGE_PROPERTIES_RENT = 'UPDATE_HAS_NEXT_NEXT_PAGE_PROPERTIES_RENT'

export const PROPERTY_SEARCH_RENT_REQUEST = 'PROPERTY_SEARCH_RENT_REQUEST'
export const PROPERTY_SEARCH_RENT_SUCCESS = 'PROPERTY_SEARCH_RENT_SUCCESS'
export const PROPERTY_SEARCH_RENT_FAILED = 'PROPERTY_SEARCH_RENT_FAILED' 

export const PROPERTY_SEARCH_BUY_REQUEST = 'PROPERTY_SEARCH_BUY_REQUEST'
export const PROPERTY_SEARCH_BUY_SUCCESS = 'PROPERTY_SEARCH_BUY_SUCCESS'
export const PROPERTY_SEARCH_BUY_FAILED = 'PROPERTY_SEARCH_BUY_FAILED' 

export const MAKE_REQUEST_PROPERTIES_BUY = 'MAKE_REQUEST_PROPERTIES_BUY'
export const UPDATE_HAS_NEXT_PAGE_PROPERTIES_BUY = 'UPDATE_HAS_NEXT_PAGE_PROPERTIES_BUY'
export const UPDATE_HAS_NEXT_NEXT_PAGE_PROPERTIES_BUY = 'UPDATE_HAS_NEXT_NEXT_PAGE_PROPERTIES_BUY'

export const ADD_CUSTOM_PROPERTIES_REPORT = 'ADD_CUSTOM_PROPERTIES_REPORT'
export const CUSTOM_PROPERTIES_REPORT_LOADING = 'CUSTOM_PROPERTIES_REPORT_LOADING'
export const CUSTOM_PROPERTIES_REPORT_FAILED = 'CUSTOM_PROPERTIES_REPORT_FAILED'
export const CUSTOM_PROPERTIES_CLEAR_ARRAY = 'CUSTOM_PROPERTIES_CLEAR_ARRAY'

export const MAKE_REQUEST_PROPERTIES = 'MAKE_REQUEST_PROPERTIES'
export const UPDATE_HAS_NEXT_PAGE_PROPERTIES = 'UPDATE_HAS_NEXT_PAGE_PROPERTIES'
export const UPDATE_HAS_NEXT_NEXT_PAGE_PROPERTIES = 'UPDATE_HAS_NEXT_NEXT_PAGE_PROPERTIES'

/* 
    Favorites
*/
export const FAVOURITES_LOADING = 'FAVOURITES_LOADING'
export const FAVOURITES_FAILED = 'FAVOURITES_FAILED'
export const DELETE_FAVOURITE = 'DELETE_FAVOURITE'
export const ADD_FAVOURITES = 'ADD_FAVOURITES'


/* 
    Review
*/
export const ADD_REVIEW = 'ADD_REVIEW'
export const ADD_REVIEWS = 'ADD_REVIEWS'
export const REVIEWS_FAILED = 'REVIEWS_FAILED'

export const FETCH_SINGLE_REVIEW_REQUEST = 'FETCH_SINGLE_REVIEW_REQUEST'
export const FETCH_SINGLE_REVIEW_SUCCESS = 'FETCH_SINGLE_REVIEW_SUCCESS'
export const FETCH_SINGLE_REVIEW_FAILED = 'FETCH_SINGLE_REVIEW_FAILED' 
export const FETCH_SINGLE_REVIEW_RESET = 'FETCH_SINGLE_REVIEW_RESET' 

export const REVIEW_EDIT_REQUEST = 'REVIEW_EDIT_REQUEST'
export const REVIEW_EDIT_SUCCESS = 'REVIEW_EDIT_SUCCESS'
export const REVIEW_EDIT_FAILED = 'REVIEW_EDIT_FAILED'
export const REVIEW_EDIT_RESET = 'REVIEW_EDIT_RESET'

export const REVIEW_DELETE_REQUEST = 'REVIEW_DELETE_REQUEST'
export const REVIEW_DELETE_SUCCESS = 'REVIEW_DELETE_SUCCESS'
export const REVIEW_DELETE_FAILED = 'REVIEW_DELETE_FAILED'

/* 
    Login - Logout
*/
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

/* 
    Signup
*/
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

/* 
    Alert
*/
export const ALERT_SUCCESS = 'ALERT_SUCCESS'
export const ALERT_ERROR = 'ALERT_ERROR'
export const ALERT_CLEAR = 'ALERT_CLEAR'

/* 
    User 
*/
export const USERS_LOADING = 'USERS_LOADING'
export const USERS_FAILED = 'USERS_FAILED'
export const ADD_USERS = 'ADD_USERS'
export const ADD_USER = 'ADD_USER'
export const USER_LOADING = 'USER_LOADING'
export const USER_FAILED = 'USER_FAILED'

export const USER_FETCH_SINGLE_REQUEST = 'USER_FETCH_SINGLE_REQUEST'
export const USER_FETCH_SINGLE_SUCCESS = 'USER_FETCH_SINGLE_SUCCESS'
export const USER_FETCH_SINGLE_FAILED = 'USER_FETCH_SINGLE_FAILED'
export const USER_FETCH_SINGLE_RESET = 'USER_FETCH_SINGLE_RESET'

export const USER_EDIT_REQUEST = 'USER_EDIT_REQUEST'
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS'
export const USER_EDIT_FAILED = 'USER_EDIT_FAILED'
export const USER_EDIT_RESET = 'USER_EDIT_RESET'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED'

export const ADD_CUSTOM_USERS_REPORT = 'ADD_CUSTOM_USERS_REPORT'
export const CUSTOM_USERS_REPORT_LOADING = 'CUSTOM_USERS_REPORT_LOADING'
export const CUSTOM_USERS_REPORT_FAILED = 'CUSTOM_USERS_REPORT_FAILED'
export const CUSTOM_USERS_CLEAR_ARRAY = 'CUSTOM_USERS_CLEAR_ARRAY'

export const MAKE_REQUEST = 'MAKE_REQUEST'
export const UPDATE_HAS_NEXT_PAGE = 'UPDATE_HAS_NEXT_PAGE'
export const UPDATE_HAS_NEXT_NEXT_PAGE = 'UPDATE_HAS_NEXT_NEXT_PAGE'

/* 
    Fee
*/
export const ADD_FEES = 'ADD_FEES'
export const FEES_LOADING = 'FEES_LOADING'
export const FEES_FAILED = 'FEES_FAILED'

export const FEE_CREATE_REQUEST = 'FEE_CREATE_REQUEST'
export const FEE_CREATE_SUCCESS = 'FEE_CREATE_SUCCESS'
export const FEE_CREATE_FAILED = 'FEE_CREATE_FAILED' 

export const FEE_DELETE_REQUEST = 'FEE_DELETE_REQUEST'
export const FEE_DELETE_SUCCESS = 'FEE_DELETE_SUCCESS'
export const FEE_DELETE_FAILED = 'FEE_DELETE_FAILED'

export const FEE_EDIT_REQUEST = 'FEE_EDIT_REQUEST'
export const FEE_EDIT_SUCCESS = 'FEE_EDIT_SUCCESS'
export const FEE_EDIT_FAILED = 'FEE_EDIT_FAILED'

export const FEE_FETCH_SINGLE_REQUEST = 'FEE_FETCH_SINGLE_REQUEST'
export const FEE_FETCH_SINGLE_SUCCESS = 'FEE_FETCH_SINGLE_SUCCESS'
export const FEE_FETCH_SINGLE_FAILED = 'FEE_FETCH_SINGLE_FAILED'
export const FEE_FETCH_SINGLE_RESET = 'FEE_FETCH_SINGLE_RESET'

export const MAKE_REQUEST_FEES = 'MAKE_REQUEST_FEES'
export const UPDATE_HAS_NEXT_PAGE_FEES = 'UPDATE_HAS_NEXT_PAGE_FEES'
export const UPDATE_HAS_NEXT_NEXT_PAGE_FEES = 'UPDATE_HAS_NEXT_NEXT_PAGE_FEES'

/* 
    Sales
*/
export const ADD_SALES = 'ADD_SALES'
export const SALES_LOADING = 'SALES_LOADING'
export const SALES_FAILED = 'SALES_FAILED'
export const ADD_TODAY_SALES = 'ADD_TODAY_SALES'
export const SALES_TODAY_LOADING = 'SALES_TODAY_LOADING'
export const SALES_TODAY_FAILED = 'SALES_TODAY_FAILED'
export const ADD_MINUS7_SALES = 'ADD_MINUS7_SALES'
export const SALES_MINUS7_LOADING = 'SALES_MINUS7_LOADING'
export const SALES_MINUS7_FAILED = 'SALES_MINUS7_FAILED'
export const ADD_MINUS14_SALES = 'ADD_MINUS14_SALES'
export const SALES_MINUS14_LOADING = 'SALES_MINUS14_LOADING'
export const SALES_MINUS14_FAILED = 'SALES_MINUS14_FAILED'
export const ADD_MINUS21_SALES = 'ADD_MINUS21_SALES'
export const SALES_MINUS21_LOADING = 'SALES_MINUS21_LOADING'
export const SALES_MINUS21_FAILED = 'SALES_MINUS21_FAILED'
export const ADD_MINUS28_SALES = 'ADD_MINUS28_SALES'
export const SALES_MINUS28_LOADING = 'SALES_MINUS28_LOADING'
export const SALES_MINUS28_FAILED = 'SALES_MINUS28_FAILED'
export const ADD_MINUS35_SALES = 'ADD_MINUS35_SALES'
export const SALES_MINUS35_LOADING = 'SALES_MINUS35_LOADING'
export const SALES_MINUS35_FAILED = 'SALES_MINUS35_FAILED'

export const SALE_CREATE_REQUEST = 'SALE_CREATE_REQUEST'
export const SALE_CREATE_SUCCESS = 'SALE_CREATE_SUCCESS'
export const SALE_CREATE_FAILED = 'SALE_CREATE_FAILED' 

export const SALE_DELETE_REQUEST = 'SALE_DELETE_REQUEST'
export const SALE_DELETE_SUCCESS = 'SALE_DELETE_SUCCESS'
export const SALE_DELETE_FAILED = 'SALE_DELETE_FAILED'

export const SALE_EDIT_REQUEST = 'SALE_EDIT_REQUEST'
export const SALE_EDIT_SUCCESS = 'SALE_EDIT_SUCCESS'
export const SALE_EDIT_FAILED = 'SALE_EDIT_FAILED'

export const SALE_FETCH_SINGLE_REQUEST = 'SALE_FETCH_SINGLE_REQUEST'
export const SALE_FETCH_SINGLE_SUCCESS = 'SALE_FETCH_SINGLE_SUCCESS'
export const SALE_FETCH_SINGLE_FAILED = 'SALE_FETCH_SINGLE_FAILED'
export const SALE_FETCH_SINGLE_RESET = 'SALE_FETCH_SINGLE_RESET'

export const MAKE_REQUEST_SALES = 'MAKE_REQUEST_SALES'
export const UPDATE_HAS_NEXT_PAGE_SALES = 'UPDATE_HAS_NEXT_PAGE_SALES'
export const UPDATE_HAS_NEXT_NEXT_PAGE_SALES = 'UPDATE_HAS_NEXT_NEXT_PAGE_SALES'

/* 
    Contract
*/
export const ADD_CONTRACTS_LAST_MONTH = 'ADD_CONTRACTS_LAST_MONTH'
export const CONTRACTS_LAST_MONTH_LOADING = 'CONTRACTS_LAST_MONTH_LOADING'
export const CONTRACTS_LAST_MONTH_FAILED = 'CONTRACTS_LAST_MONTH_FAILED'

export const CONTRACT_CREATE_REQUEST = 'CONTRACT_CREATE_REQUEST'
export const CONTRACT_CREATE_SUCCESS = 'CONTRACT_CREATE_SUCCESS'
export const CONTRACT_CREATE_FAILED = 'CONTRACT_CREATE_FAILED' 

export const CONTRACT_DELETE_REQUEST = 'CONTRACT_DELETE_REQUEST'
export const CONTRACT_DELETE_SUCCESS = 'CONTRACT_DELETE_SUCCESS'
export const CONTRACT_DELETE_FAILED = 'CONTRACT_DELETE_FAILED'

export const CONTRACT_EDIT_REQUEST = 'CONTRACT_EDIT_REQUEST'
export const CONTRACT_EDIT_SUCCESS = 'CONTRACT_EDIT_SUCCESS'
export const CONTRACT_EDIT_FAILED = 'CONTRACT_EDIT_FAILED'

export const CONTRACT_FETCH_SINGLE_REQUEST = 'CONTRACT_FETCH_SINGLE_REQUEST'
export const CONTRACT_FETCH_SINGLE_SUCCESS = 'CONTRACT_FETCH_SINGLE_SUCCESS'
export const CONTRACT_FETCH_SINGLE_FAILED = 'CONTRACT_FETCH_SINGLE_FAILED'
export const CONTRACT_FETCH_SINGLE_RESET = 'CONTRACT_FETCH_SINGLE_RESET'

export const CONTRACTS_LOADING = 'CONTRACTS_LOADING'
export const CONTRACTS_FAILED = 'CONTRACTS_FAILED'
export const ADD_CONTRACTS = 'ADD_CONTRACTS' 

export const ADD_CUSTOM_CONTRACTS_REPORT = 'ADD_CUSTOM_CONTRACTS_REPORT'
export const CUSTOM_CONTRACTS_REPORT_LOADING = 'CUSTOM_CONTRACTS_REPORT_LOADING'
export const CUSTOM_CONTRACTS_REPORT_FAILED = 'CUSTOM_CONTRACTS_REPORT_FAILED'
export const CUSTOM_CONTRACTS_CLEAR_ARRAY = 'CUSTOM_CONTRACTS_CLEAR_ARRAY'

export const MAKE_REQUEST_CONTRACTS = 'MAKE_REQUEST_CONTRACTS'
export const UPDATE_HAS_NEXT_PAGE_CONTRACTS = 'UPDATE_HAS_NEXT_PAGE_CONTRACTS'
export const UPDATE_HAS_NEXT_NEXT_PAGE_CONTRACTS = 'UPDATE_HAS_NEXT_NEXT_PAGE_CONTRACTS'

/* 
    Profit
*/
export const ADD_PROFIT_LAST_MONTH = 'ADD_PROFIT_LAST_MONTH'
export const PROFIT_LAST_MONTH_LOADING = 'PROFIT_LAST_MONTH_LOADING'
export const PROFIT_LAST_MONTH_FAILED = 'PROFIT_LAST_MONTH_FAILED'
export const ADD_PROFIT_THIS_YEAR = 'ADD_PROFIT_THIS_YEAR'
export const PROFIT_THIS_YEAR_LOADING = 'PROFIT_THIS_YEAR_LOADING'
export const PROFIT_THIS_YEAR_FAILED = 'PROFIT_THIS_YEAR_FAILED'
export const ADD_NEW_USERS_LAST_MONTH = 'ADD_NEW_USERS_LAST_MONTH'
export const LAST_MONTH_NEW_USERS_LOADING = 'LAST_MONTH_NEW_USERS_LOADING'
export const LAST_MONTH_NEW_USERS_FAILED = 'LAST_MONTH_NEW_USERS_FAILED'
export const ADD_CUSTOM_PROFIT_REPORT = 'ADD_CUSTOM_PROFIT_REPORT'
export const CUSTOM_PROFIT_REPORT_LOADING = 'CUSTOM_PROFIT_REPORT_LOADING'
export const CUSTOM_PROFIT_REPORT_FAILED = 'CUSTOM_PROFIT_REPORT_FAILED'
export const CUSTOM_PROFIT_CLEAR_ARRAY = 'CUSTOM_PROFIT_CLEAR_ARRAY'

/* 
    Landlord
*/
export const ADD_LANDLORDS = 'ADD_LANDLORDS'
export const LANDLORDS_LOADING = 'LANDLORDS_LOADING'
export const LANDLORDS_FAILED = 'LANDLORDS_FAILED'

export const LANDLORD_CREATE_REQUEST = 'LANDLORD_CREATE_REQUEST'
export const LANDLORD_CREATE_SUCCESS = 'LANDLORD_CREATE_SUCCESS'
export const LANDLORD_CREATE_FAILED = 'LANDLORD_CREATE_FAILED' 

export const LANDLORD_DELETE_REQUEST = 'LANDLORD_DELETE_REQUEST'
export const LANDLORD_DELETE_SUCCESS = 'LANDLORD_DELETE_SUCCESS'
export const LANDLORD_DELETE_FAILED = 'LANDLORD_DELETE_FAILED'

export const LANDLORD_EDIT_REQUEST = 'LANDLORD_EDIT_REQUEST'
export const LANDLORD_EDIT_SUCCESS = 'LANDLORD_EDIT_SUCCESS'
export const LANDLORD_EDIT_FAILED = 'LANDLORD_EDIT_FAILED'

export const LANDLORD_FETCH_SINGLE_REQUEST = 'LANDLORD_FETCH_SINGLE_REQUEST'
export const LANDLORD_FETCH_SINGLE_SUCCESS = 'LANDLORD_FETCH_SINGLE_SUCCESS'
export const LANDLORD_FETCH_SINGLE_FAILED = 'LANDLORD_FETCH_SINGLE_FAILED'
export const LANDLORD_FETCH_SINGLE_RESET = 'LANDLORD_FETCH_SINGLE_RESET'

export const MAKE_REQUEST_LANDLORDS = 'MAKE_REQUEST_LANDLORDS'
export const UPDATE_HAS_NEXT_PAGE_LANDLORDS = 'UPDATE_HAS_NEXT_PAGE_LANDLORDS'
export const UPDATE_HAS_NEXT_NEXT_PAGE_LANDLORDS = 'UPDATE_HAS_NEXT_NEXT_PAGE_LANDLORDS'


/* 
    Offers
*/
export const ADD_OFFERS = 'ADD_OFFERS'
export const OFFERS_LOADING = 'OFFERS_LOADING'
export const OFFERS_FAILED = 'OFFERS_FAILED'

export const OFFER_CREATE_REQUEST = 'OFFER_CREATE_REQUEST'
export const OFFER_CREATE_SUCCESS = 'OFFER_CREATE_SUCCESS'
export const OFFER_CREATE_FAILED = 'OFFER_CREATE_FAILED' 

export const OFFER_MODIFY_REQUEST = 'OFFER_MODIFY_REQUEST'
export const OFFER_MODIFY_SUCCESS = 'OFFER_MODIFY_SUCCESS'
export const OFFER_MODIFY_FAILED = 'OFFER_MODIFY_FAILED' 

export const REMOVE_OFFER_REQUEST = 'REMOVE_OFFER_REQUEST'
export const REMOVE_OFFER_SUCCESS = 'REMOVE_OFFER_SUCCESS'
export const REMOVE_OFFER_FAILED = 'REMOVE_OFFER_FAILED'

export const ACCEPT_OFFER_REQUEST = 'ACCEPT_OFFER_REQUEST'
export const ACCEPT_OFFER_SUCCESS = 'ACCEPT_OFFER_SUCCESS'
export const ACCEPT_OFFER_FAILED = 'ACCEPT_OFFER_FAILED'

export const DECLINE_OFFER_REQUEST = 'DECLINE_OFFER_REQUEST'
export const DECLINE_OFFER_SUCCESS = 'DECLINE_OFFER_SUCCESS'
export const DECLINE_OFFER_FAILED = 'DECLINE_OFFER_FAILED'

/* 
    Viewings
*/
export const ADD_VIEWINGS = 'ADD_VIEWINGS'
export const VIEWINGS_LOADING = 'VIEWINGS_LOADING'
export const VIEWINGS_FAILED = 'VIEWINGS_FAILED'

export const VIEWING_CREATE_REQUEST = 'VIEWING_CREATE_REQUEST'
export const VIEWING_CREATE_SUCCESS = 'VIEWING_CREATE_SUCCESS'
export const VIEWING_CREATE_FAILED = 'VIEWING_CREATE_FAILED' 

export const DELETE_VIEWING_REQUEST = 'DELETE_VIEWING_REQUEST'
export const DELETE_VIEWING_SUCCESS = 'DELETE_VIEWING_SUCCESS'
export const DELETE_VIEWING_FAILED = 'DELETE_VIEWING_FAILED'

/* 
    Notifications
*/
export const ADD_NOTIFICATIONS = 'ADD_NOTIFICATIONS'
export const NOTIFICATIONS_LOADING = 'NOTIFICATIONS_LOADING'
export const NOTIFICATIONS_FAILED = 'NOTIFICATIONS_FAILED'
export const NOTIFICATION_NEW_TOGGLE = 'NOTIFICATION_NEW_TOGGLE '

export const NOTIFICATION_CREATE_REQUEST = 'NOTIFICATION_CREATE_REQUEST'
export const NOTIFICATION_CREATE_SUCCESS = 'NOTIFICATION_CREATE_SUCCESS'
export const NOTIFICATION_CREATE_FAILED = 'NOTIFICATION_CREATE_FAILED' 

export const NOTIFICATION_DELETE_REQUEST = 'NOTIFICATION_DELETE_REQUEST'
export const NOTIFICATION_DELETE_SUCCESS = 'NOTIFICATION_DELETE_SUCCESS'
export const NOTIFICATION_DELETE_FAILED = 'NOTIFICATION_DELETE_FAILED' 

/* 
    Appointments 
*/
export const APPOINTMENTS_LOADING = 'APPOINTMENTS_LOADING'
export const APPOINTMENTS_FAILED = 'APPOINTMENTS_FAILED'
export const ADD_APPOINTMENTS = 'ADD_APPOINTMENTS'

export const ADD_APPOINTMENT_LOADING = 'ADD_APPOINTMENT_LOADING'
export const ADD_APPOINTMENT_SUCCESS = 'ADD_APPOINTMENT_SUCCESS'
export const ADD_APPOINTMENT_FAILED = 'ADD_APPOINTMENT_FAILED'

export const APPOINTMENT_EDIT_REQUEST = 'APPOINTMENT_EDIT_REQUEST'
export const APPOINTMENT_EDIT_SUCCESS = 'APPOINTMENT_EDIT_SUCCESS'
export const APPOINTMENT_EDIT_FAILED = 'APPOINTMENT_EDIT_FAILED'

export const DELETE_APPOINTMENT_REQUEST = 'DELETE_APPOINTMENT_REQUEST'
export const DELETE_APPOINTMENT_SUCCESS = 'DELETE_APPOINTMENT_SUCCESS'
export const DELETE_APPOINTMENT_FAILED = 'DELETE_APPOINTMENT_FAILED'